name: MyFirstMCPlugin
version: 1.0
main: io.github.dino060311.Main
api-version: 1.20
author: dino060311
description: Bukkit API를 활용한 첫 번째 마인크래프트 서버 플러그인 프로젝트입니다.
commands:
  메뉴:
    description: 직업 선택 GUI 메뉴를 엽니다.
  타이머:
    description: 파밍 시간 보스바 타이머를 시작합니다.
  npc소환:
    description: 제자리에 고정된 스토리 NPC를 소환합니다.
  시한폭탄:
    description: 투척형 시한폭탄을 꺼냅니다.
  마법지팡이:
    description: 화염 마법 지팡이를 꺼냅니다.
  컷신:
    description: 극적인 화면 고정 연출을 테스트합니다.
  랜덤직업:
    description: 직업을 선택하는 메뉴 창을 엽니다.
  무기대장장이:
    description: 거래가 가능한 무기 대장장이 NPC를 소환합니다.
  서버명령어:
    description: 서버의 특수 능력을 안내합니다.